# -*- coding: utf-8 -*-
"""Country_data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TvDUuWWxxY2qTG3WOEXf0Kzrvs1PEBJi
"""

import pandas as pd
file_path='Country_data (1).xlsx'
data=pd.read_excel(file_path)
data.info()
data.head(10)

data.isnull().sum()

data.isnull().values.any()

data.duplicated()

data.dtypes

data[['income','gdpp']]=data[['income','gdpp']].astype(float)

data.dtypes

data['income'].skew()
#If result > +1 → highly right skewed
#If result ≈ 0 → normal
#If result < -1 → left skewed

import matplotlib.pyplot as plt

plt.hist(data['income'], bins=30)
plt.title("Income Distribution")
plt.show()

Q1=data['income'].quantile(0.25)
Q3=data['income'].quantile(0.75)
IQR=Q3-Q1
lower=Q1-1.5*IQR
upper=Q3+1.5*IQR

data['income'] = data['income'].clip(lower, upper)

import numpy as np
data['income'] = np.log1p(data['income'])
#Makes distribution more balanced
#Reduces skewness further

data['income'].skew()

import matplotlib.pyplot as plt

plt.hist(data['income'], bins=30)
plt.title("Income Distribution")
plt.show()

print(data['income'].skew())
#Not highly skewed anymore
#Close to normal distribution
#Outliers impact is already reduced

print(data['gdpp'].skew())
print(data['gdpp'].mean())
print(data['gdpp'].median())

import matplotlib.pyplot as plt

plt.hist(data['gdpp'], bins=30)
plt.title("GDPP Distribution")
plt.show()

Q1=data['gdpp'].quantile(0.25)
Q3=data['gdpp'].quantile(0.75)
IQR=Q3-Q1
lower=Q1-1.5*IQR
upper=Q3+1.5*IQR

data['gdpp']=data['gdpp'].clip(lower,upper)

import numpy as np
data['gdpp'] = np.log1p(data['gdpp'])

print(data['gdpp'].skew())

import matplotlib.pyplot as plt

plt.hist(data['child_mort'], bins=30)
plt.title("child_mort")
plt.show()

print(data['child_mort'].skew())
print(data['child_mort'].mean())
print(data['child_mort'].median())

Q1=data['child_mort'].quantile(0.25)
Q3=data['child_mort'].quantile(0.75)
IQR=Q3-Q1
lower=Q1-1.5*IQR
upper=Q3+1.5*IQR

data['child_mort']=data['child_mort'].clip(lower,upper)

data['child_mort'] = np.log1p(data['child_mort'])

data['child_mort'].skew()
#Child mortality is highly right skewed due to a few countries with very high mortality rates.
#After capping and log transformation, the distribution becomes approximately symmetric.”

data['inflation'].skew()

Q1 = data['inflation'].quantile(0.25)
Q3 = data['inflation'].quantile(0.75)
IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

data['inflation'] = data['inflation'].clip(-5, 30)

data['inflation'].skew()

import numpy as np

data['inflation'] = np.sign(data['inflation']) * np.log1p(abs(data['inflation']))

data['inflation'].skew()
#After capping and applying a signed log transformation, inflation skewness changed from highly right skewed (~5.15) to left skewed (~-2.25).
# This indicates that extreme values have been controlled, and further transformation is not necessary.”

numeric_data = data.select_dtypes(include=['number'])
(numeric_data < 0).sum()

data['Development_Index'] = (data['income'] + data['gdpp'] + data['life_expec']) / data['child_mort']

data['Trade_Balance'] = data['exports'] - data['imports']

data['Health_Impact_Ratio'] = data['health'] / data['child_mort']

"""#Univariate Analysis

"""

import seaborn as sns
import matplotlib.pyplot as plt

sns.histplot(data['income'], kde=True)
plt.title("Income Distribution")
plt.show()
#Distribution of income
#Income is positively skewed (right-skewed)
#Majority of countries have low income
#Few countries have extremely high income
#Presence of outliers (rich countries)

plt.hist(data['child_mort'], bins=20)
plt.xlabel('Child Mortality')
plt.ylabel('Number of Countries')
plt.title('Distribution of Child Mortality')
plt.show()
#The distribution of child mortality is highly right-skewed,
#indicating that most countries have low child mortality rates,
 #while a few countries exhibit extremely high mortality.
 #This highlights significant global disparities in healthcare and living conditions###

plt.hist(data['life_expec'], bins=20)
plt.xlabel('Life Expectancy')
plt.ylabel('Number of Countries')
plt.title('Distribution of Life Expectancy')
plt.show()
#The distribution of life expectancy is slightly left-skewed,
# with most countries having high life expectancy between 65 and 80 years.
# A few countries show significantly lower values, indicating disparities in healthcare and living conditions across the world.

plt.hist(data['gdpp'], bins=20)
plt.xlabel('GDP per capita')
plt.ylabel('Number of Countries')
plt.title('Distribution of GDP per Capita')
plt.show()
#The distribution of GDP per capita is highly right-skewed,
 #with most countries having low to moderate GDP values and a few countries exhibiting extremely high GDP.
 #The wide spread indicates significant economic inequality across countries.

plt.hist(data['total_fer'], bins=20)
plt.xlabel('Fertility Rate')
plt.ylabel('Number of Countries')
plt.title('Distribution of Fertility Rate')
plt.show()
#The distribution of fertility rate is positively skewed, with most countries having low to moderate fertility levels,
#while a few countries exhibit very high fertility rates.
# This reflects significant differences in economic development, healthcare, and population growth patterns across countries.

"""# Bivariate / Multivariate Analysis

"""

#Income vs Life Expectancy
plt.scatter(data['income'], data['life_expec'])
plt.xlabel('Income')
plt.ylabel('Life Expectancy')
plt.title('Income vs Life Expectancy')
plt.show()
#Positive correlation
#Higher income → Higher life expectancy

plt.scatter(data['health'], data['child_mort'])
plt.xlabel('Health Expenditure (% of GDP)')
plt.ylabel('Child Mortality')
plt.title('Health Expenditure vs Child Mortality')
plt.show()
#Negative Correlation,As health expenditure increases,Child mortality decreases

#GDP vs Fertility Rate
plt.scatter(data['gdpp'], data['total_fer'])
plt.xlabel('GDP per capita')
plt.ylabel('Fertility Rate')
plt.title('gdp vs total_fertility')
plt.show()
#Strong Negative Correlation,As GDP per capita increases.Fertility rate decreases

#Inflation vs GDP
plt.scatter(data['inflation'], data['gdpp'])
plt.xlabel('inflation')
plt.ylabel('gdpp per capital')
plt.title('inflation vs gdpp')
plt.show()
#Countries with both high and low GDP exhibit varying inflation rates,
# indicating that inflation is influenced by short-term economic conditions rather than long-term economic development.
#Inflation does not consistently increase or decrease with GDP,Pattern looks scattered/random

#Trade Balance vs Income
plt.scatter(data['Trade_Balance'], data['income'])
plt.xlabel('trade_balance')
plt.ylabel('income')
plt.title('trade_balance vs income')
plt.show()
#Countries with both high and low income levels can experience either trade surplus or deficit,
#indicating that income is influenced by multiple economic factors beyond trade balance.

"""# Correlation Analysis

"""

#Correlation heatmap
# select only numeric columns
corr = data.corr(numeric_only=True)

plt.figure(figsize=(10,8))
sns.heatmap(corr, annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()
# positive corelation
#income ↔ gdpp,income ↔ life_expec,gdpp ↔ life_expec (Rich countries → better living conditions)

"""1.Identify strongest predictors of life expectancy and mortality.

*   Higher income & GDP → better healthcare, nutrition → longer life
*  Countries with high mortality & fertility → lower life expectancy

# Rule-Based Country Segmentation
"""

conditions = [
    (data['child_mort'] > 80) & (data['income'] < 5000),
    (data['income'] > 30000) & (data['life_expec'] > 78),
    (data['income'].between(8000, 30000)),
    (data['inflation'] > 15),
    (data['health'] < 5) & (data['child_mort'] > 70),
    (data['gdpp'] < 2000)
]

choices = [
    "High Risk Country",
    "Developed Nation",
    "Emerging Economy",
    "High Inflation Risk",
    "Health Critical",
    "Low GDP Trap"
]

data['Segment'] = np.select(conditions, choices, default="Other")

data.info()

"""# SQL"""

import sqlite3

conn_sqlite = sqlite3.connect("Country_database.sqlite")
cursor = conn_sqlite.cursor()

print("SQLite connection established!")

data.to_sql('country_stats', conn_sqlite, index=False, if_exists='replace')

query = """
SELECT
    Segment,
    COUNT(*) AS Country_Count,
    AVG(income) AS Avg_Income,
    AVG(gdpp) AS Avg_GDPP,
    AVG(child_mort) AS Avg_Child_Mort,
    AVG(life_expec) AS Avg_Life_Expectancy,
    AVG(inflation) AS Avg_Inflation
FROM country_data
GROUP BY Segment
ORDER BY Country_Count DESC;
"""

kpi = pd.read_sql(query, conn_sqlite)
kpi

"""# New Section"""